// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Yv7_psl3wUuGoEvRjnpZggR3CGzmZ0w',
    appId: '1:383493268051:web:2d124ff20825546f115ca6',
    messagingSenderId: '383493268051',
    projectId: 'nismile-a575c',
    authDomain: 'nismile-a575c.firebaseapp.com',
    databaseURL: 'https://nismile-a575c-default-rtdb.firebaseio.com',
    storageBucket: 'nismile-a575c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJv8UIa5TMjS_tV5MBJBa-r4LNEW7Agtw',
    appId: '1:383493268051:android:a6c8d9c1224a86d7115ca6',
    messagingSenderId: '383493268051',
    projectId: 'nismile-a575c',
    databaseURL: 'https://nismile-a575c-default-rtdb.firebaseio.com',
    storageBucket: 'nismile-a575c.firebasestorage.app',
  );

}